[project]
name = "dso-ai-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "astronomy-engine>=2.1.19",
    "astropy>=6.1.7",
    "logfire>=4.14.2",
    "pydantic-ai>=1.18.0",
]
